### ISSUE TITLE
Unicode input for symbols with multiple characters

### ISSUE THREAD

**Issue by pnlph** [banacorn/agda-mode#102]
Posted by error in the official agda-mode for emacs:
https://github.com/agda/agda/issues/3868

**Comment by pdelano** [comment]
If you're in Atom and you want to make the typing easier, you can use an Atom snippet.  After I defined the snippet (pasting the Unicode characters, not the ascii abbreviation, into the definition of the snippet, I can just type "eqb<Tab>"  to insert the Unicode sequence ≡⟨⟩ into the file I'm editing in agda-mode.  Define similar snippets according to your taste.

**Comment by banacorn** [comment]
Thank you for reporting this!

Currently there are a few ways of leaving the unicode input mode:
* Interrupt by making a "wrong" sequence
* Press <kbd>ECS</kbd>
* Click your mouse somewhere else

I think it's a really good idea to use backslashes `\` as a mean to exit and re-enter the input mode as you proposed in  agda/agda#3868! (And it turned out that I've been typing `≡⟨⟩` unconsciously with that stupid way all the time)

@pdelano actually I have a bunch of those equation reasoning stuff baked in somewhere XD https://github.com/banacorn/language-agda/blob/master/snippets/language-agda.cson

**Comment by banacorn** [comment]
`v0.9.3`
