### ISSUE TITLE
Query Unicode Characters

### ISSUE THREAD

**Issue by subttle** [banacorn/agda-mode#46]
As described here: http://wiki.portal.chalmers.se/agda/pmwiki.php?n=Docs.UnicodeInput
When editing Agda in Emacs, one may position their cursor over a character and press `C-u C-x = ` or `M-x describe-char` to learn how to input the character in question. If this feature is available in Atom I am not aware of it. I would really appreciate having this functionality for Atom. The character input sequences have been changing a bit lately, and this would really help me keep up because as it stands now, I have to occasionally switch to Emacs for a couple minutes every now and then to do this, or stick to copy/paste every time I need the character.
Perhaps I should open a separate ticket for this, but I haven't been able to input `\.` (which produces `∙` in Emacs) as of late, even though Emacs says that is how to input it (and it used to work a few months ago, not sure what version changed this). Thank you for your consideration.

**Comment by banacorn** [comment]
That `C-u C-x =` feature is a thing I've been longing for. It seems to me that the functionality is provided by some emacs-rull-them-all-input-method-manager sorta thing. In other words, it comes for free on Emacs, but that's not the case on Atom.

It's possible to implement this on Atom, perhaps by building an inverse of the keymap, and it should n't be that hard because I've all these mappings generated by [this code](https://github.com/banacorn/Folge) ... which leads to the next issue.

I'm terribly sorry about the turmoil caused by the changes to the keymap months ago. 
agda-mode's keymap is drawn from two other keymaps (some main keymap + some extensions), 
If you look closely at `\.` you should see there are 2 candidates, and the good old `∙` should have been placed as the first candidate. It seems like I have failed to prioritize the main keymap over the extension one.

Thanks for reporting this! I will try to fix this before returning to duty (conscripted, it sucks :()

**Comment by banacorn** [comment]
Give `C-u C-x =` a try! 😬
