### ISSUE TITLE
Uncaught unknown command agda-mode:info

### ISSUE THREAD

**Issue by subttle** [banacorn/agda-mode#53]
Hi, thank you for maintaining this awesome project. When attempting to load an Agda file (`C-c C-l`), I receive `Connection Error - Unable to find Agda on your machine, please enter the path of Agda manually.` But it continues to ask even if I input the correct path. If I attempt to use `Packages > Agda Mode > Info` then I receive an error.

> Uncaught unknown command agda-mode:info
> /home/<user>/.atom/packages/agda-mode/lib/parser/command.js:123

Under settings the "Internal state gibberish" reads: `{"connections":[],"erred":[null,null]}` and "Executable Path" is filled out correctly. I have verified the Agda executable file is there and I do not believe it is a permissions issue because everything works fine if I roll back to Atom 1.18 and agda-mode 0.6.15.

Additionally, I should add that I haven't had any luck getting agda-mode to work with Atom on Linux since agda-mode >0.6.15 and Atom >=1.19. Perhaps Atom's async save changes introduced in Atom 1.19 may have something to do with this (just a feeling/guess, to be honest)?
 https://github.com/banacorn/agda-mode/issues/48

OS: Linux (RPM based)
Atom: 1.21.1 x64
agda-mode: 0.7.4
language-agda: 0.2.5
Agda: 2.5.3

**Comment by banacorn** [comment]
1. `Packages > Agda Mode > Info` was removed in the last version, but I forgot to take it out from the menu. Click on the 'settings' button at the top right corner of the panel and fiddle around and you should see the good old info at the 'Protocol'.

2. If filling the absolute path of Agda doesn't work, could you please paste me the result of `agda --version` (is it `Agda version 2.5.3`?) because agda-mode may not recognize the provided program as Agda and thus keep asking you to provide another path.

3. Could you elaborate a bit more on the problem you get when on Linux since agda-mode > 0.6.1 and Atom >= 1.19?

Thank you and sorry for all these inconvenience :o

**Comment by subttle** [comment]
1. Ah, I see.
2.
> $ agda --version
> Agda version 2.5.3
3. Sure. Originally when I updated to Atom 1.19 I could still load a file without error, however, the goals were not showing up formatted, they only loaded as plaintext `{! !}`. I will try to update in a bit with better information.

**Comment by subttle** [comment]
I upgraded from Fedora 28 to Fedora 29 (with Atom 1.32.1, Agda 2.5.4.1) and tried again and it seems to be working again, so I think I should close this now! Unfortunately I'm not sure what the problem was but it seems to be fixed for me now, I'm commenting this just in case anyone else had the same issue :D
