### ISSUE TITLE
undo history grouping

### ISSUE THREAD

**Issue by Zambonifofex** [banacorn/agda-mode#82]
It seems like undoing in Agda files with this package installed groups two “undo groups” together.

For example, if, in a file, I write `abc`, then, after the “undo grouping interval” time (from the editor setting in Atom), I write `def` (to get `abcdef`), I’d expect undoing would remove “def”, whereas it removes the whole `abcdef`. If I then redo, Atom will put only `abc` back.

**Comment by banacorn** [comment]
I've overridden the original undoing process, because some command such as `case` involves many stages of rewriting, and I want them to be grouped as a single action. 

But somehow it's broken after some updates. I'm going to reimplement and fix it on the [`ocaml`](https://github.com/banacorn/agda-mode/tree/ocaml) branch.

**Comment by Zambonifofex** [comment]
Hello! I think that it’s interesting to note that [Atom actually has this functionality built into its API][transact], so you probably don’t really actually need to override the default undoing action.

[transact]: https://atom.io/docs/api/latest/TextEditor#instance-transact

**Comment by banacorn** [comment]
Thanks!!

**Comment by banacorn** [comment]
Should be fixed in 1b506e692c623158e073ea809cc818854c10f49b!
